### ISSUE TITLE
Hot Reloading Setup

### ISSUE THREAD

**Issue by SnoutBug** [unitoftime/flow#1]
How did you setup your hot reloading?
I have a module MyModule which contains packages `main`, `package_a` and `package_b`

package `main` imports `package_a`
`package_a` imports `package_b`

- When I change something, like adding a line of code to any function inside package `main` I see the the changes represented immediately after using `plugin.Check`
- Changing something inside `package_a` I only see a change, if the change was modifying a string for example.
- Changing anything inside `package_b` does not yield any changes.

Is there anything I need to pay attention to when building the plugin? Is this something that works in your case? Or is this out of scope for you?

**Comment by unitoftime** [comment]
You can look at the example here: https://github.com/unitoftime/flow/tree/master/example/hot

Added in this commit: https://github.com/unitoftime/flow/commit/ee19890828f0aab44a0c6f073211c319b6745627

Thanks.
